'use strict';
const $=s=>document.querySelector(s),t=(key,params)=>I18n.t(key,params),h=(key,params)=>I18n.html(key,params);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const GROUP_KEYS=['nonpolar','polar','acidic','basic','special'];
const GROUPS=Object.fromEntries(GROUP_KEYS.map(key=>[key,t('groups.'+key)]));
const MODE_KEYS=['mix','names','class','structure','properties','history'];
const MODES=Object.fromEntries(MODE_KEYS.map(key=>[key,t('modes.'+key)]));
const TOPIC_ICONS={mix:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',names:'<path d="M3 4h9l9 9-8 8-10-10V4Z"/><circle cx="7.5" cy="8" r="1"/><path d="m11 11 5 5m-7-2 4 4"/>',class:'<path d="M3 3h18l-7 8v8l-4 2V11L3 3Z"/>',structure:'<path d="m12 2 8.5 5v10L12 22l-8.5-5V7L12 2Z"/><circle cx="12" cy="12" r="5"/>',history:'<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4V4Zm9 3a3 3 0 0 1 3-3h5v15h-4a4 4 0 0 0-4 2M7 8h3m-3 4h3m6-4h2m-2 4h2"/>'};
function topicIcon(key){if(TOPIC_ICONS[key])return `<svg viewBox="0 0 24 24" focusable="false" aria-hidden="true">${TOPIC_ICONS[key]}</svg>`;return '<span class="properties-symbol">±</span>';}
const AXES={aromatic:{title:t('groups.aromatic'),codes:'FWYH'},aliphatic:{title:t('groups.aliphatic'),codes:'AVLIM'},sulfur:{title:t('groups.sulfur'),codes:'CM'},bcaa:{title:t('groups.bcaa'),codes:'VLI'},hydroxyl:{title:t('groups.hydroxyl'),codes:'STY'},amide:{title:t('groups.amide'),codes:'NQ'}};
const TYPES=ExamCore.TOPICS.flatMap(topic=>topic.types),TRAIN_TOPIC={names:'names-codes',class:'classification',structure:'structures',properties:'properties',history:'history'};
const KEY='amino-quiz-v1';let memoryOnly=false,stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{memoryOnly=true;}
let stats=stored.stats&&typeof stored.stats==='object'?stored.stats:{},mistakes=Array.isArray(stored.mistakes)?stored.mistakes.filter(x=>AMINO.some(a=>a.code===x.code)&&TYPES.includes(x.type)).map(({code,type,confusedCode})=>({code,type,confusedCode:AMINO.some(a=>a.code===confusedCode)?confusedCode:null})):[],rounds=Number(stored.rounds)||0,extended=!!stored.extended,difficulty=stored.difficulty==='hard'?'hard':'normal';
let representation=['mixed','2d','3d'].includes(stored.representation)?stored.representation:'mixed';
let mode='mix',view='train',session=null,search='',filter='all';
const getA=code=>AMINO.find(a=>a.code===code),pool=()=>AMINO.filter(a=>extended||a.group!=='special');
const activeMistakes=()=>mistakes.filter(x=>pool().some(a=>a.code===x.code&&ExamCore.allowed(a,x.type))),shuffle=arr=>[...arr].map(v=>({v,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.v);
function save(){try{localStorage.setItem(KEY,JSON.stringify({stats,mistakes,rounds,extended,difficulty,representation}));}catch{memoryOnly=true;}}
function totals(){return Object.values(stats).reduce((sum,x)=>({attempts:sum.attempts+(Number(x.attempts)||0),correct:sum.correct+(Number(x.correct)||0)}),{attempts:0,correct:0});}
function accuracy(){const value=totals();return value.attempts?Math.round(value.correct/value.attempts*100)+'%':'—';}
function languageLocked(){const practice=!!session&&!session.done,exam=typeof examState!=='undefined'&&(examBusy||pendingAnswer||examState?.status==='running'||examAttempts?.some(a=>a.status==='running'));return practice||exam;}
function updateLanguageControl(){const select=$('#language-select');if(!select)return;select.disabled=languageLocked();select.value=I18n.locale;document.querySelectorAll('[data-view]').forEach(button=>button.disabled=typeof examBusy!=='undefined'&&examBusy);select.title=t('language.label');}
window.aminoLanguageLocked=languageLocked;window.updateLanguageControl=updateLanguageControl;
function setView(next){if(view!==next)window.aminoAnalytics?.section(next);view=next;session=null;document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===next));render();window.scrollTo(0,0);}
function intro(k,title,sub){return `<div class="intro">${k?`<div class="eyebrow">${esc(k)}</div>`:''}<h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div>`;}
function render(){document.body.classList.toggle('in-quiz',!!session&&!session.done);$('#app').innerHTML=(memoryOnly?`<div class="save-warning">${h('practice.storageWarning')}</div>`:'')+(view==='library'?library():view==='progress'?progress():session?quiz():home());bind();bindImageViews();bindRepresentations();updateLanguageControl();}
function home(){const totalsValue=totals(),day=AMINO[Math.floor(Date.now()/86400000)%20],repeat=activeMistakes().length;return intro('',t('practice.title'),'')+`<div class="workspace"><section class="panel start-panel"><div class="round-head"><h2><span class="step">1</span>${h('practice.topic')}</h2><span class="round-badge">${h('practice.tenQuestions')}</span></div><div class="mode-grid">${Object.entries(MODES).map(([key,label])=>`<button class="mode ${mode===key?'selected':''}" data-mode="${key}" aria-pressed="${mode===key}"><span class="mode-symbol" aria-hidden="true">${topicIcon(key)}</span><span>${esc(label)}</span><span class="selection-mark" aria-hidden="true">${mode===key?'✓':''}</span></button>`).join('')}</div><div class="select-row set-row"><span class="step-label" id="set-label"><span class="step">2</span>${h('practice.set')}</span><div class="set-segments" role="group" aria-labelledby="set-label"><button type="button" data-set="20" aria-pressed="${!extended}">${h('practice.standardSet')}</button><button type="button" data-set="22" aria-pressed="${extended}" title="${h('practice.allSetTitle')}">${h('practice.allSet')}</button></div></div>${difficultyControls('practice-difficulty',3,false)}${['mix','class','structure','properties'].includes(mode)?representationControls():''}<button id="start" class="button full primary-action">${h('practice.start')}</button></section><section class="panel context-panel"><div class="section-top"><h2>${h('practice.statistics')}</h2><span class="pill">${h('practice.rounds',{count:rounds})}</span></div><div class="mini-stats"><div><span class="big-number">${totalsValue.attempts}</span><small>${h('practice.answers')}</small></div><div><span class="big-number">${accuracy()}</span><small>${h('practice.accuracy')}</small></div><div><span class="big-number">${repeat}</span><small>${h('practice.toReview')}</small></div></div><div class="section-top"><h3>${h('practice.aminoOfDay')}</h3><button class="text-button" data-detail="${day.code}">${h('common.open')}</button></div><div class="molecule-tile"><img src="${esc(day.structure)}" alt="${h('library.structureAlt',{name:day.name})}"><div><div class="code">${day.code} <small>${day.three}</small></div><strong>${esc(day.name)}</strong></div></div><p class="tip">${esc(day.info)}</p><button class="button secondary full" id="repeat" ${repeat?'':'disabled'} style="margin-top:20px">${repeat?h('practice.repeatMistakesCount',{count:repeat}):h('practice.repeatMistakes')}</button></section></div>`;}
function typesFor(a){const types=mode==='mix'?TYPES:ExamCore.TOPICS.find(topic=>topic.id===TRAIN_TOPIC[mode]).types;return types.filter(type=>ExamCore.allowed(a,type));}
function start(repeat=false){
  const settings={representation};
  let questions=[];
  if(repeat)questions=shuffle(activeMistakes()).slice(0,10).map(x=>ExamCore.question(pool(),getA(x.code),x.type,Math.random,{...settings,confusedCode:x.confusedCode}));
  else{
    const topic=ExamCore.TOPICS.find(item=>item.id===TRAIN_TOPIC[mode]),used=new Set();
    const directionTypes=direction=>{const types=shuffle(topic[direction]);return Array.from({length:5},(_,i)=>types[i%types.length]);};
    const schedule=mode==='mix'?shuffle(['forward','reverse'].flatMap(direction=>shuffle(ExamCore.TOPICS).map(item=>shuffle(item[direction])[0]))):shuffle([...directionTypes('forward'),...directionTypes('reverse')]);
    questions=schedule.map(type=>{
      const candidates=pool().filter(a=>typesFor(a).includes(type)),unseen=candidates.filter(a=>!used.has(a.code)),a=shuffle(unseen.length?unseen:candidates)[0];
      used.add(a.code);return ExamCore.question(pool(),a,type,Math.random,settings);
    });
  }
  if(!questions.length)return;
  questions=questions.map(q=>ExamCore.withDifficulty(pool(),q,difficulty));
  window.aminoAnalytics?.goal('training_start',{topic:mode,repeat,difficulty});
  session={topic:mode,repeat,difficulty,questions,index:0,correct:0,answered:false,selected:null,selectedId:null,results:[],done:false};render();window.scrollTo(0,0);
}
function representationControls(){return `<div class="select-row representation-row"><label for="representation">${h('representations.label')}</label><select id="representation">${['mixed','2d','3d'].map(key=>`<option value="${key}" ${representation===key?'selected':''}>${h('representations.'+key)}</option>`).join('')}</select></div>`;}
function bindRepresentations(){const select=$('#representation');if(select)select.onchange=()=>{representation=select.value;save();};}
function promptIsImage(q){return q.promptKind==='image'||q.type==='structure';}
function choicesAreImages(q){return q.choiceKind==='image'||q.type==='structure-reverse';}
function imageTools(q){return choicesAreImages(q)?`<button type="button" class="text-button image-tools" data-enlarge-choices>${h('representations.zoomChoices')}</button>`:'';}
function bindImageViews(){
  document.querySelectorAll('[data-enlarge-image]').forEach(button=>button.onclick=()=>modal(`<h2>${h('representations.enlarged')}</h2><img class="enlarged-structure" src="${esc(button.dataset.enlargeImage)}" alt="${h('accessibility.structurePrompt')}">`));
  const button=$('[data-enlarge-choices]');
  if(button)button.onclick=()=>{const q=examState?examScreenQuestion:session?.questions[session.index];if(q)modal(`<h2>${h('representations.enlarged')}</h2><div class="enlarged-options">${q.choices.map((src,i)=>`<figure><figcaption>${i+1}</figcaption><img src="${esc(src)}" alt="${h('library.structureOptionAlt',{number:i+1})}"></figure>`).join('')}</div>`);};
}
function promptMarkup(q){return promptIsImage(q)?`<button type="button" class="image-prompt" data-enlarge-image="${esc(q.prompt)}" aria-label="${h('representations.zoom')}"><img src="${esc(q.prompt)}" alt="${h('accessibility.structurePrompt')}"></button>`:esc(q.prompt);}
function promptClass(q){return promptIsImage(q)?'image-display':q.promptKind==='formula'?'formula-display':['property','classset-reverse','history','history-code'].includes(q.type)?'description':['name','name-three'].includes(q.type)?'':'words';}
function choicesClass(q){return choicesAreImages(q)?'structure-answers':['property-forward','classset','class-image','property-image','history-forward'].includes(q.type)?'answer-descriptions':'';}
function choiceMarkup(q,value,i){return choicesAreImages(q)?`<span class="structure-number" aria-hidden="true">${i+1}</span><img class="structure-option" src="${esc(value)}" alt="${h('library.structureOptionAlt',{number:i+1})}">`:esc(value);}
function reviewMarkup(q,value){return choicesAreImages(q)?`<img class="review-structure" src="${esc(value)}" alt="${h('accessibility.structurePrompt')}">`:esc(value);}
function questionTopic(q){const topic=ExamCore.TOPICS.find(topic=>topic.types.includes(q.type));return Object.keys(TRAIN_TOPIC).find(key=>TRAIN_TOPIC[key]===topic?.id)||'names';}
function questionFoot(q,exam=false){if(q.note?.endsWith('-classification'))return questionFoot({...q,note:q.note.replace('-classification','')},exam).replace(/\.$/,'')+'. '+t(exam?'exam.classNote':'practice.classNote');return q.note==='model'?t('practice.structureNote')+'. '+t('representations.modelNote'):q.note==='sidechain'?t('representations.sidechainNote'):q.note==='structure'||['structure','structure-reverse'].includes(q.type)?t('practice.structureNote'):['classset','classset-reverse','category'].includes(q.type)?t(exam?'exam.classNote':'practice.classNote'):'';}
function difficultyControls(id,step=0,help=true){return `<div class="select-row set-row difficulty-row"><span class="step-label" id="${id}-label">${step?`<span class="step">${step}</span>`:''}${h('difficulty.label')}</span><div class="set-segments" role="group" aria-labelledby="${id}-label">${['normal','hard'].map(value=>`<button type="button" data-difficulty="${value}" aria-pressed="${difficulty===value}">${h('difficulty.'+value)}</button>`).join('')}</div>${help&&difficulty==='hard'?`<p class="difficulty-description">${h('difficulty.description')}</p>`:''}</div>`;}
function bindDifficulty(){document.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>{const value=button.dataset.difficulty;if(value===difficulty)return;difficulty=value;save();if(view==='leaderboard')loadRanking();else render();document.querySelector(`[data-difficulty="${value}"]`)?.focus({preventScroll:true});});}
function textAnswerForm(q,id,selected='',locked=false,right=null){return `<form id="${id}" class="text-answer-form ${right===true?'correct':right===false?'wrong':''}"><label for="${id}-input">${h('difficulty.inputLabel')}</label><div class="text-answer-row"><input id="${id}-input" name="answer" type="text" required maxlength="120" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" placeholder="${h('difficulty.placeholder.'+q.answerKind)}" aria-describedby="${id}-hint" value="${esc(selected)}" ${locked?'disabled':''}><button class="button" type="submit" ${locked?'disabled':''}>${h('difficulty.submit')}</button></div><p id="${id}-hint" class="text-answer-hint">${h('difficulty.hint')}${q.answerKind==='name'?' '+h('difficulty.nameHint'):''}</p></form>`;}
function textAnswerFeedback(q,feedback){return q.answerMode==='text'&&!feedback.right&&q.type!=='classset-reverse'?`<p class="text-answer-correct">${h('common.correctAnswer')}: <b>${reviewMarkup(q,feedback.correct)}</b></p>`:'';}
function focusTextAnswer(){const input=$('.text-answer-form input:not(:disabled)');if(input&&document.activeElement?.tagName!=='INPUT')input.focus({preventScroll:true});}
function quiz(){
  if(session.done)return result();
  const q=session.questions[session.index],correctId=q.correctId??q.correct,right=session.right;
  const answers=q.answerMode==='text'?textAnswerForm(q,'practice-answer',session.selected||'',session.answered,session.answered?right:null):`<div class="answers ${choicesClass(q)}">${q.choices.map((choice,i)=>{const id=q.choiceIds?.[i]??choice,correct=id===correctId,selected=id===session.selectedId;return `<button class="answer ${session.answered?(correct?'correct':selected?'wrong':''):''}" data-answer="${i}" ${session.answered?'disabled':''}><span class="letter" aria-hidden="true">${session.answered&&correct?'✓':session.answered&&selected?'×':i+1}</span><span class="answer-copy">${choiceMarkup(q,choice,i)}${session.answered&&correct?`<small>${h('common.correctAnswer')}</small>`:session.answered&&selected?`<small>${h('common.yourAnswer')}</small>`:''}</span></button>`;}).join('')}</div>`;
  return `<div class="quiz-wrap"><div class="quiz-toolbar"><button id="exit" class="text-button">${h('practice.finish')}</button><span>${h('practice.questionProgress',{current:session.index+1,total:session.questions.length})}</span><span>${h('practice.correctCount',{count:session.correct})}</span></div>${session.difficulty==='hard'?`<span class="difficulty-badge">${h('difficulty.hard')}</span>`:''}<div class="bar" aria-label="${h('practice.roundProgress')}"><span style="width:${session.index/session.questions.length*100}%"></span></div><section class="panel question-panel ${session.answered?'':'question-enter'}"><span class="eyebrow">${h('practice.topicLabels.'+questionTopic(q))}</span><h1>${esc(q.text)}</h1><div class="prompt-display ${promptClass(q)}">${promptMarkup(q)}</div>${answers}${imageTools(q)}${session.answered?`<div class="feedback ${right?'':'bad'}" role="status"><strong><span aria-hidden="true">${right?'✓':'×'}</span> ${h(right?'common.correct':'common.error')}</strong>${textAnswerFeedback(q,{right,correct:q.correct})}<p>${esc(session.explanation||q.explanation)}</p>${historySources(q)}<button id="next" class="button">${h(session.index+1===session.questions.length?'common.viewResult':'common.nextQuestion')}</button></div>`:''}</section>${questionFoot(q)?`<div class="quiz-foot">${esc(questionFoot(q))}</div>`:''}</div>`;
}
function answer(i){if(!session||session.answered||session.done)return;const q=session.questions[session.index];if(q.answerMode==='text'||!Number.isInteger(i)||q.choices[i]===undefined)return;const selected=q.choices[i],selectedId=q.choiceIds?.[i]??selected;recordPracticeAnswer(selected,selectedId,selectedId===(q.correctId??q.correct));}
function answerText(value){if(!session||session.answered||session.done||typeof value!=='string'||!ExamCore.normalizeAnswer(value)||value.length>120)return;const q=session.questions[session.index];if(q.answerMode!=='text')return;const right=ExamCore.checkTextAnswer(q,value);const other=right?null:AMINO.find(a=>(q.answerKind==='name'?ExamCore.answerNames(a):[a[q.answerKind]]).filter(Boolean).some(name=>ExamCore.normalizeAnswer(name)===ExamCore.normalizeAnswer(value)));recordPracticeAnswer(value.trim(),right?q.correctId:other?'amino:'+other.code:null,right);}
function recordPracticeAnswer(selected,selectedId,right){const q=session.questions[session.index],a=getA(q.code),correctId=q.correctId??q.correct;session.selected=selected;session.selectedId=selectedId;session.right=right;session.answered=true;session.explanation=ExamCore.answerExplanation(q,selectedId);if(right)session.correct++;session.results.push({...q,right,selected,selectedId,correct:q.correct,correctId});const st=stats[a.code]||{attempts:0,correct:0};st.attempts++;if(right)st.correct++;stats[a.code]=st;mistakes=mistakes.filter(x=>x.code!==q.code||x.type!==q.type);if(!right){const confusedCode=AMINO.find(other=>['amino:','structure:','property:','code:','history:'].some(prefix=>selectedId===prefix+other.code)||selectedId==='three:'+other.three)?.code;mistakes.push({code:q.code,type:q.type,confusedCode});}save();render();requestAnimationFrame(()=>{$('#next')?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#next')?.focus({preventScroll:true});});}
function next(){if(!session?.answered||session.done)return;session.index++;if(session.index>=session.questions.length){session.done=true;window.aminoAnalytics?.goal('training_complete',{topic:session.topic,repeat:session.repeat,difficulty:session.difficulty});rounds++;save();}else{session.answered=false;session.selected=null;session.selectedId=null;session.right=null;}render();window.scrollTo(0,0);}
function result(){const wrong=session.results.filter(item=>!item.right);return `<div class="result">${intro('',t('common.result'),'')}${session.difficulty==='hard'?`<span class="difficulty-badge">${h('difficulty.hard')}</span>`:''}<section class="panel"><div class="result-score">${session.correct}<span class="muted" style="font-size:30px;letter-spacing:0"> / ${session.questions.length}</span></div><p class="muted">${h('practice.percentCorrect',{percent:Math.round(session.correct/session.questions.length*100)})}</p><div class="result-actions"><button id="start" class="button">${h('practice.anotherRound')}</button>${activeMistakes().length?`<button id="repeat" class="button secondary">${h('practice.repeatMistakes')}</button>`:''}</div>${wrong.map(item=>`<div class="review-item"><strong>${esc(getA(item.code).name)}</strong>${esc(item.text)}<br><span class="muted">${h('practice.yourAnswer')} ${reviewMarkup(item,item.selected)}</span><br>${item.type==='classset-reverse'?esc(item.explanation):h('practice.correctWas')+' '+reviewMarkup(item,item.correct)}</div>`).join('')}</section></div>`;}
function library(){const needle=search.toLocaleLowerCase(I18n.locale).trim(),list=pool().filter(a=>(filter==='all'||a.group===filter||AXES[filter]?.codes.includes(a.code))&&`${ExamCore.answerNames(a).join(' ')} ${a.code} ${a.three}`.toLocaleLowerCase(I18n.locale).includes(needle));return intro('',t('library.title',{count:pool().length}),'')+`<div class="tools"><input id="search" type="search" placeholder="${h('library.searchPlaceholder')}" aria-label="${h('library.searchLabel')}" value="${esc(search)}"><select id="filter" aria-label="${h('library.filterLabel')}"><option value="all">${h('library.allGroups')}</option>${Object.entries({...GROUPS,...Object.fromEntries(Object.entries(AXES).map(([key,value])=>[key,value.title]))}).filter(([key])=>extended||key!=='special').map(([key,label])=>`<option value="${key}" ${filter===key?'selected':''}>${esc(label)}</option>`).join('')}</select></div>${classificationMap()}<div class="catalog">${list.map(a=>`<button class="amino-card" data-detail="${a.code}"><div class="card-top"><span class="card-code">${a.code}</span><span class="card-three">${a.three}</span></div><img src="${esc(a.structure)}" alt=""><h3>${esc(a.name)}</h3>${groupPill(a.group,GROUPS[a.group])}</button>`).join('')||`<div class="empty">${h('library.nothing')}</div>`}</div>`;}
function progress(){const total=totals(),covered=pool().filter(a=>stats[a.code]?.attempts).length;return intro('',t('progress.title'),'')+`<div class="overview"><div class="panel"><span class="big-number">${total.attempts}</span><small>${h('progress.answersTotal')}</small></div><div class="panel"><span class="big-number">${accuracy()}</span><small>${h('practice.accuracy')}</small></div><div class="panel"><span class="big-number">${covered}/${pool().length}</span><small>${h('progress.inTraining')}</small></div></div><div class="section-top"><h2>${h('progress.byAmino')}</h2><button id="repeat" class="text-button" ${activeMistakes().length?'':'disabled'}>${h('progress.mistakes',{count:activeMistakes().length})}</button></div><div class="progress-list">${pool().map(a=>{const st=stats[a.code]||{attempts:0,correct:0},pct=st.attempts?Math.round(st.correct/st.attempts*100):0;return `<div class="progress-row"><div class="section-top" style="margin:0"><strong>${a.three} · ${esc(a.name)}</strong><span class="muted">${st.attempts?pct+'%':'—'}</span></div><div class="bar"><span style="width:${pct}%"></span></div><div class="sr-status" style="margin-top:8px">${h('progress.rowStatus',{correct:st.correct,attempts:st.attempts})}</div></div>`;}).join('')}</div><p class="catalog-note">${h('progress.note')}</p><button id="reset" class="reset">${h('progress.reset')}</button>`;}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}
function historySources(q){return q.type.startsWith('history')?historyLinks(getA(q.code)?.history):'';}
function historyLinks(history){if(!history?.sources?.length)return '';return `<p class="history-sources">${h('common.sources')}: ${history.sources.map((url,i)=>{let label=url;try{label=new URL(url).hostname.replace(/^www\./,'');}catch{}return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}${history.sources.length>1?' · '+(i+1):''}</a>`;}).join(' · ')}</p>`;}
function historyDetail(a){return a.history?`<section class="history-story"><h2>${h('library.historyTitle')}</h2><p>${esc(a.history.story)}</p>${historyLinks(a.history)}</section>`:'';}
function detail(code,variant=0){const a=getA(code),wiki=a.links?.wikipedia,styles=ExamCore.imageStyles(a),style=styles[variant%styles.length],src=ExamCore.imageFor(a,style);modal(`<article class="detail">${groupPill(a.group,GROUPS[a.group])}<h1 style="font-size:30px">${esc(a.name)}</h1>${a.name!==a.en?`<div class="muted">${esc(a.en)}</div>`:''}<div class="detail-codes"><strong>${a.code}</strong><span class="muted">/</span><strong>${a.three}</strong></div><img src="${esc(src)}" alt="${h('library.structureAlt',{name:a.name})}"><button id="next-structure" class="text-button" type="button">${h('representations.next')} · ${variant%styles.length+1}/${styles.length}</button>${style?.startsWith('ball')?`<p class="muted">${h('representations.modelNote')}</p>`:''}${tags(a)}<div class="facts"><div class="fact"><small>${h('library.side')}</small><strong>${esc(a.side)}</strong></div><div class="fact"><small>${h('library.feature')}</small>${esc(a.feature)}</div><div class="fact"><small>${h('library.diet')}</small>${h(a.essential===null?'library.dietUnknown':a.essential?'library.essential':'library.notEssential')}</div></div><p>${esc(a.info)}</p>${historyDetail(a)}${wiki?`<p><a href="${esc(wiki)}" target="_blank" rel="noopener noreferrer">${h('library.wikipedia')}</a></p>`:''}<p class="muted">${h('library.neutralNote')}</p></article>`);$('#next-structure').onclick=()=>{detail(code,variant+1);$('#next-structure').focus({preventScroll:true});};}
function help(){const links=[['https://en.wikipedia.org/wiki/Amino_acid#Classification','help.sourceClassification'],['https://en.wikipedia.org/wiki/Proteinogenic_amino_acid#Side-chain_properties','help.sourceProperties'],['https://www.ncbi.nlm.nih.gov/books/NBK9879/','help.sourceCells'],['https://www.ncbi.nlm.nih.gov/books/NBK557845/','help.sourceEssential'],['https://www.ncbi.nlm.nih.gov/books/NBK538201/','help.sourceHistidine'],['https://pubchem.ncbi.nlm.nih.gov/','help.sourcePubchem']];modal(`<h2>${h('help.title')}</h2><p>${h('help.sets')}</p><h3>${h('help.classificationTitle')}</h3><p>${h('help.classification1')}</p><p>${h('help.classification2')}</p><h3>${h('help.structuresTitle')}</h3><p>${h('help.structures')}</p><h3>${h('help.historyTitle')}</h3><p>${h('help.history')}</p><h3>${h('help.sourcesTitle')}</h3><p>${links.map(([url,key])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${h(key)}</a>`).join('<br>')}</p><p class="muted">${h('help.stored')}</p>`);}
function groupMarker(group){return `<span class="group-marker ${group}" aria-hidden="true">${({nonpolar:'●',aliphatic:'●',polar:'◆',acidic:'−',basic:'+',special:'✦',aromatic:'⬡',sulfur:'S',bcaa:'Y',hydroxyl:'OH',amide:'N'})[group]||'●'}</span>`;}
function groupPill(group,label){return `<span class="pill ${group}">${groupMarker(group)}${esc(label)}</span>`;}
function tags(a){return `<div class="tags">${Object.entries(AXES).filter(([,value])=>value.codes.includes(a.code)).map(([key,value])=>groupPill(key,value.title)).join('')}${a.essential?`<span class="pill">${h('library.essential')}</span>`:''}${'RCQYGP'.includes(a.code)?`<span class="pill">${h('library.conditionallyEssential')}</span>`:''}</div>`;}
function classificationMap(){const groups=[['aliphatic',t('groups.aliphatic'),'AVLIM'],['aromatic',t('groups.aromatic'),'FWYH'],['polar',t('groups.polarMap'),'CSTNQY'],['basic',t('groups.basicMap'),'KRH'],['acidic',t('groups.acidicMap'),'DE']];return `<details class="map"><summary>${h('library.groupsSummary')}</summary><p class="catalog-note">${h('library.groupsNote')}</p><div class="map-grid">${groups.map(([key,label,codes])=>`<button class="map-group ${key}" data-group="${key}"><strong>${groupMarker(key)}${esc(label)}</strong><span>${codes.split('').map(code=>getA(code).three).join(' · ')}</span></button>`).join('')}</div></details>`;}
function bind(){bindDifficulty();if($('#practice-answer'))$('#practice-answer').onsubmit=event=>{event.preventDefault();answerText(event.currentTarget.elements.answer.value);};focusTextAnswer();document.querySelectorAll('[data-group]').forEach(button=>button.onclick=()=>{filter=button.dataset.group;search='';render();});document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;render();});document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>detail(button.dataset.detail));document.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>answer(Number(button.dataset.answer)));document.querySelectorAll('[data-set]').forEach(button=>button.onclick=()=>{const value=button.dataset.set;extended=value==='22';filter='all';save();render();document.querySelector(`[data-set="${value}"]`).focus({preventScroll:true});});if($('#start'))$('#start').onclick=()=>start();if($('#repeat'))$('#repeat').onclick=()=>start(true);if($('#next'))$('#next').onclick=next;if($('#exit'))$('#exit').onclick=()=>modal(`<h2>${h('practice.finishTitle')}</h2><p>${h('practice.finishBody')}</p><button id="confirm-exit" class="button dark">${h('practice.finishAction')}</button>`);if($('#search'))$('#search').oninput=e=>{const caret=e.target.selectionStart;search=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(caret,caret);};if($('#filter'))$('#filter').onchange=e=>{filter=e.target.value;render();};if($('#reset'))$('#reset').onclick=()=>modal(`<h2>${h('progress.resetTitle')}</h2><p>${h('progress.resetBody')}</p><button id="confirm-reset" class="button dark">${h('progress.resetAction')}</button>`);}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{if(session&&!session.done)modal(`<h2>${h('practice.leaveTitle')}</h2><p>${h('practice.leaveBody')}</p><button id="confirm-view" class="button dark" data-target="${esc(button.dataset.view)}">${h('practice.leaveAction')}</button>`);else setView(button.dataset.view);});
$('#help').onclick=help;$('.brand').onclick=e=>{e.preventDefault();$('[data-view="train"]').click();};$('#close-modal').onclick=()=>$('#modal').close();
$('#modal').addEventListener('click',e=>{const button=e.target.closest('button');if(button?.id==='confirm-exit'){$('#modal').close();setView('train');}if(button?.id==='confirm-view'){$('#modal').close();setView(button.dataset.target);}if(button?.id==='confirm-reset'){stats={};mistakes=[];rounds=0;save();$('#modal').close();render();}});
document.addEventListener('keydown',e=>{if($('#modal').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(session&&!session.done){if(!session.answered&&/^[1-4]$/.test(e.key))answer(Number(e.key)-1);else if(session.answered&&e.key==='Enter'){e.preventDefault();next();}}});
render();
